---
fixtures:
  repositories:
    acl: "git://github.com/puppetlabs/puppetlabs-acl"
    registry: "git://github.com/puppetlabs/puppetlabs-registry"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    windowsfeature: "git://github.com/voxpupuli/puppet-windowsfeature"
    local_security_policy: "git://github.com/ayohrling/local_security_policy"
  forge_modules:
    auditpol: "jonono-auditpol"
