---
fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    registry: "git://github.com/puppetlabs/puppetlabs-registry"
    local_security_policy: "git://github.com/ayohrling/local_security_policy"
  forge_modules:
    auditpol: "jonono-auditpol"
