#
# This module secures windows
#
class secure_windows (
  Optional[Boolean] $is_dod,
  Optional[String] $classification,
) {

  # Platform-specific defaults
  case $facts['operatingsystemmajrelease'] {

    '2012','2012 R2': {
      class { '::secure_windows::stig::v1073': }
      class { '::secure_windows::stig::v1075': }
      class { '::secure_windows::stig::v1081': }
      class { '::secure_windows::stig::v1089': }
      class { '::secure_windows::stig::v1090': }
      class { '::secure_windows::stig::v1093': }
      class { '::secure_windows::stig::v1097': }
      class { '::secure_windows::stig::v1098': }
      class { '::secure_windows::stig::v1099': }
      class { '::secure_windows::stig::v1102': }
      class { '::secure_windows::stig::v1104': }
      class { '::secure_windows::stig::v1105': }
      class { '::secure_windows::stig::v1107': }
      class { '::secure_windows::stig::v1112': }
      class { '::secure_windows::stig::v1113': }
      class { '::secure_windows::stig::v1114': }
      class { '::secure_windows::stig::v1115': }
      class { '::secure_windows::stig::v1120': }
      class { '::secure_windows::stig::v1121': }
      class { '::secure_windows::stig::v1136': }
      class { '::secure_windows::stig::v1141': }
      class { '::secure_windows::stig::v1145': }
      class { '::secure_windows::stig::v1150': }
      class { '::secure_windows::stig::v1151': }
      class { '::secure_windows::stig::v1152': }
      class { '::secure_windows::stig::v1153': }
      class { '::secure_windows::stig::v1154': }
      class { '::secure_windows::stig::v1155': }
      class { '::secure_windows::stig::v1157': }
      class { '::secure_windows::stig::v1162': }
      class { '::secure_windows::stig::v1163': }
      class { '::secure_windows::stig::v1164': }
      class { '::secure_windows::stig::v1165': }
      class { '::secure_windows::stig::v1166': }
      class { '::secure_windows::stig::v1171': }
      class { '::secure_windows::stig::v1172': }
      class { '::secure_windows::stig::v1173': }
      class { '::secure_windows::stig::v1174': }
      class { '::secure_windows::stig::v2372': }
      class { '::secure_windows::stig::v2374': }
      class { '::secure_windows::stig::v2376': }
      class { '::secure_windows::stig::v3337': }
      class { '::secure_windows::stig::v3338': }
      class { '::secure_windows::stig::v3339': }
      class { '::secure_windows::stig::v3340': }
      class { '::secure_windows::stig::v3343': }
      class { '::secure_windows::stig::v3344': }
      class { '::secure_windows::stig::v3373': }
      class { '::secure_windows::stig::v3374': }
      class { '::secure_windows::stig::v3376': }
      class { '::secure_windows::stig::v3377': }
      class { '::secure_windows::stig::v3378': }
      class { '::secure_windows::stig::v3472': }
      class { '::secure_windows::stig::v11806': }
      class { '::secure_windows::stig::v14225': }
      class { '::secure_windows::stig::v14228': }
      class { '::secure_windows::stig::v14229': }
      class { '::secure_windows::stig::v14230': }
      class { '::secure_windows::stig::v14232': }
      class { '::secure_windows::stig::v14234': }
      class { '::secure_windows::stig::v14235': }
      class { '::secure_windows::stig::v14236': }
      class { '::secure_windows::stig::v14237': }
      class { '::secure_windows::stig::v14239': }
      class { '::secure_windows::stig::v14240': }
      class { '::secure_windows::stig::v14241': }
      class { '::secure_windows::stig::v14242': }
      class { '::secure_windows::stig::v14243': }
      class { '::secure_windows::stig::v14247': }
      class { '::secure_windows::stig::v14249': }
      class { '::secure_windows::stig::v14253': }
      class { '::secure_windows::stig::v14259': }
      class { '::secure_windows::stig::v14260': }
      class { '::secure_windows::stig::v14261': }
      class { '::secure_windows::stig::v14268': }
      class { '::secure_windows::stig::v14269': }
      class { '::secure_windows::stig::v14270': }
      class { '::secure_windows::stig::v14831': }
      class { '::secure_windows::stig::v15666': }
      class { '::secure_windows::stig::v15680': }
      class { '::secure_windows::stig::v15727': }
      class { '::secure_windows::stig::v15991': }
      class { '::secure_windows::stig::v15997': }
      class { '::secure_windows::stig::v15998': }
      class { '::secure_windows::stig::v15999': }
      class { '::secure_windows::stig::v16000': }
      class { '::secure_windows::stig::v16008': }
      class { '::secure_windows::stig::v16020': }
      class { '::secure_windows::stig::v18010': }
      class { '::secure_windows::stig::v4443': }
      class { '::secure_windows::stig::v4445': }
      class { '::secure_windows::stig::v4447': }
      class { '::secure_windows::stig::v4448': }
      class { '::secure_windows::stig::v6831': }
      class { '::secure_windows::stig::v6832': }
      class { '::secure_windows::stig::v6833': }
      class { '::secure_windows::stig::v6834': }
      class { '::secure_windows::stig::v6836': }
      class { '::secure_windows::stig::v6840': }
      class { '::secure_windows::stig::v7002': }
      class { '::secure_windows::stig::v8316': }
      class { '::secure_windows::stig::v8317': }
      class { '::secure_windows::stig::v8322': }
      class { '::secure_windows::stig::v8324': }
      class { '::secure_windows::stig::v15667': }
      class { '::secure_windows::stig::v15672': }
      class { '::secure_windows::stig::v15674': }
      class { '::secure_windows::stig::v15682': }
      class { '::secure_windows::stig::v15683': }
      class { '::secure_windows::stig::v15684': }
      class { '::secure_windows::stig::v15685': }
      class { '::secure_windows::stig::v15686': }
      class { '::secure_windows::stig::v15687': }
      class { '::secure_windows::stig::v15696': }
      class { '::secure_windows::stig::v15697': }
      class { '::secure_windows::stig::v15698': }
      class { '::secure_windows::stig::v15699': }
      class { '::secure_windows::stig::v15700': }
      class { '::secure_windows::stig::v15701': }
      class { '::secure_windows::stig::v15702': }
      class { '::secure_windows::stig::v15703': }
      class { '::secure_windows::stig::v15704': }
      class { '::secure_windows::stig::v15705': }
      class { '::secure_windows::stig::v15706': }
      class { '::secure_windows::stig::v15707': }
      class { '::secure_windows::stig::v15713': }
      class { '::secure_windows::stig::v15718': }
      class { '::secure_windows::stig::v15722': }
      class { '::secure_windows::stig::v21950': }
      class { '::secure_windows::stig::v21951': }
      class { '::secure_windows::stig::v21952': }
      class { '::secure_windows::stig::v21953': }
      class { '::secure_windows::stig::v21954': }
      class { '::secure_windows::stig::v21955': }
      class { '::secure_windows::stig::v21956': }
      class { '::secure_windows::stig::v21960': }
      class { '::secure_windows::stig::v21961': }
      class { '::secure_windows::stig::v21963': }
      class { '::secure_windows::stig::v21964': }
      class { '::secure_windows::stig::v21965': }
      class { '::secure_windows::stig::v21967': }
      class { '::secure_windows::stig::v21969': }
      class { '::secure_windows::stig::v21970': }
      class { '::secure_windows::stig::v21971': }
      class { '::secure_windows::stig::v21973': }
      class { '::secure_windows::stig::v21980': }
      class { '::secure_windows::stig::v22692': }
      class { '::secure_windows::stig::v26070': }
      class { '::secure_windows::stig::v26283': }
      class { '::secure_windows::stig::v26359': }
      class { '::secure_windows::stig::v26469': }
      class { '::secure_windows::stig::v26470': }
      class { '::secure_windows::stig::v26472': }
      class { '::secure_windows::stig::v26473': }
      class { '::secure_windows::stig::v26474': }
      class { '::secure_windows::stig::v26476': }
      class { '::secure_windows::stig::v26478': }
      class { '::secure_windows::stig::v26479': }
      class { '::secure_windows::stig::v26480': }
      class { '::secure_windows::stig::v26481': }
      class { '::secure_windows::stig::v26482': }
      class { '::secure_windows::stig::v26483': }
      class { '::secure_windows::stig::v26484': }
      class { '::secure_windows::stig::v26485': }
      class { '::secure_windows::stig::v26486': }
      class { '::secure_windows::stig::v26488': }
      class { '::secure_windows::stig::v26489': }
      class { '::secure_windows::stig::v26490': }
      class { '::secure_windows::stig::v26492': }
      class { '::secure_windows::stig::v26493': }
      class { '::secure_windows::stig::v26494': }
      class { '::secure_windows::stig::v26496': }
      class { '::secure_windows::stig::v26497': }
      class { '::secure_windows::stig::v26498': }
      class { '::secure_windows::stig::v26499': }
      class { '::secure_windows::stig::v26500': }
      class { '::secure_windows::stig::v26501': }
      class { '::secure_windows::stig::v26503': }
      class { '::secure_windows::stig::v26504': }
      class { '::secure_windows::stig::v26506': }
      class { '::secure_windows::stig::v26529': }
      class { '::secure_windows::stig::v26530': }
      class { '::secure_windows::stig::v26531': }
      class { '::secure_windows::stig::v26533': }
      class { '::secure_windows::stig::v26535': }
      class { '::secure_windows::stig::v26537': }
      class { '::secure_windows::stig::v26538': }
      class { '::secure_windows::stig::v26539': }
      class { '::secure_windows::stig::v26540': }
      class { '::secure_windows::stig::v26541': }
      class { '::secure_windows::stig::v26542': }
      class { '::secure_windows::stig::v26543': }
      class { '::secure_windows::stig::v26546': }
      class { '::secure_windows::stig::v26547': }
      class { '::secure_windows::stig::v26548': }
      class { '::secure_windows::stig::v26549': }
      class { '::secure_windows::stig::v26550': }
      class { '::secure_windows::stig::v26551': }
      class { '::secure_windows::stig::v26552': }
      class { '::secure_windows::stig::v26553': }
      class { '::secure_windows::stig::v26555': }
      class { '::secure_windows::stig::v26557': }
      class { '::secure_windows::stig::v26558': }
      class { '::secure_windows::stig::v26600': }
      class { '::secure_windows::stig::v26602': }
      class { '::secure_windows::stig::v26604': }
      class { '::secure_windows::stig::v26605': }
      class { '::secure_windows::stig::v26606': }
      class { '::secure_windows::stig::v26575': }
      class { '::secure_windows::stig::v26576': }
      class { '::secure_windows::stig::v26577': }
      class { '::secure_windows::stig::v26578': }
      class { '::secure_windows::stig::v26579': }
      class { '::secure_windows::stig::v26580': }
      class { '::secure_windows::stig::v26581': }
      class { '::secure_windows::stig::v26582': }
      class { '::secure_windows::stig::v28504': }
      class { '::secure_windows::stig::v30016': }
#      class { '::secure_windows::stig::v32282': }
      class { '::secure_windows::stig::v33663': }
      class { '::secure_windows::stig::v33665': }
      class { '::secure_windows::stig::v34974': }
      class { '::secure_windows::stig::v36439': }
      class { '::secure_windows::stig::v36451': }
      class { '::secure_windows::stig::v36656': }
      class { '::secure_windows::stig::v36657': }
      class { '::secure_windows::stig::v36667': }
      class { '::secure_windows::stig::v36673': }
      class { '::secure_windows::stig::v36677': }
      class { '::secure_windows::stig::v36678': }
      class { '::secure_windows::stig::v36679': }
      class { '::secure_windows::stig::v36680': }
      class { '::secure_windows::stig::v36681': }
      class { '::secure_windows::stig::v36684': }
      class { '::secure_windows::stig::v36687': }
      class { '::secure_windows::stig::v36696': }
      class { '::secure_windows::stig::v36697': }
      class { '::secure_windows::stig::v36698': }
      class { '::secure_windows::stig::v36700': }
      class { '::secure_windows::stig::v36707': }
      class { '::secure_windows::stig::v36708': }
      class { '::secure_windows::stig::v36709': }
      class { '::secure_windows::stig::v36710': }
      class { '::secure_windows::stig::v36711': }
      class { '::secure_windows::stig::v36712': }
      class { '::secure_windows::stig::v36713': }
      class { '::secure_windows::stig::v36714': }
      class { '::secure_windows::stig::v36718': }
      class { '::secure_windows::stig::v36719': }
      class { '::secure_windows::stig::v36720': }
      class { '::secure_windows::stig::v36722': }
      class { '::secure_windows::stig::v36773': }
      class { '::secure_windows::stig::v36776': }
      class { '::secure_windows::stig::v36777': }
      class { '::secure_windows::stig::v39326': }
      class { '::secure_windows::stig::v39327': }
      class { '::secure_windows::stig::v39328': }
      class { '::secure_windows::stig::v39329': }
      class { '::secure_windows::stig::v39333': }
      class { '::secure_windows::stig::v39334': }
      class { '::secure_windows::stig::v40177': }
      class { '::secure_windows::stig::v40178': }
      class { '::secure_windows::stig::v40179': }
      class { '::secure_windows::stig::v40200': }
      class { '::secure_windows::stig::v40204': }
      class { '::secure_windows::stig::v40206': }
      class { '::secure_windows::stig::v42420': }
      class { '::secure_windows::stig::v43238': }
      class { '::secure_windows::stig::v43239': }
      class { '::secure_windows::stig::v43240': }
      class { '::secure_windows::stig::v43241': }
      class { '::secure_windows::stig::v43245': }
      class { '::secure_windows::stig::v57633': }
      class { '::secure_windows::stig::v57637': }
      class { '::secure_windows::stig::v57639': }
      class { '::secure_windows::stig::v57721': }
      class { '::secure_windows::stig::v72753': }
      class { '::secure_windows::stig::v73519': }
      class { '::secure_windows::stig::v73523': }
      class { '::secure_windows::stig::v73805': }
      class { '::secure_windows::stig::v78057': }
      class { '::secure_windows::stig::v78061': }
    }

    '2016','2016 R2': {
      class { '::secure_windows::stig::v73223': }
      class { '::secure_windows::stig::v73225': }
      class { '::secure_windows::stig::v73235': }
      class { '::secure_windows::stig::v73237': }
      class { '::secure_windows::stig::v73239': }
      class { '::secure_windows::stig::v73247': }
      class { '::secure_windows::stig::v73249': }
      class { '::secure_windows::stig::v73251': }
      class { '::secure_windows::stig::v73253': }
      class { '::secure_windows::stig::v73255': }
      class { '::secure_windows::stig::v73257': }
      class { '::secure_windows::stig::v73259': }
      class { '::secure_windows::stig::v73261': }
      class { '::secure_windows::stig::v73263': }
      class { '::secure_windows::stig::v73279': }
      class { '::secure_windows::stig::v73287': }
      class { '::secure_windows::stig::v73289': }
      class { '::secure_windows::stig::v73291': }
      class { '::secure_windows::stig::v73293': }
      class { '::secure_windows::stig::v73295': }
      class { '::secure_windows::stig::v73297': }
      class { '::secure_windows::stig::v73299': }
      class { '::secure_windows::stig::v73301': }
      class { '::secure_windows::stig::v73303': }
      class { '::secure_windows::stig::v73305': }
      class { '::secure_windows::stig::v73309': }
      class { '::secure_windows::stig::v73311': }
      class { '::secure_windows::stig::v73313': }
      class { '::secure_windows::stig::v73315': }
      class { '::secure_windows::stig::v73317': }
      class { '::secure_windows::stig::v73319': }
      class { '::secure_windows::stig::v73321': }
      class { '::secure_windows::stig::v73323': }
      class { '::secure_windows::stig::v73325': }
      class { '::secure_windows::stig::v73359': }
      class { '::secure_windows::stig::v73361': }
      class { '::secure_windows::stig::v73363': }
      class { '::secure_windows::stig::v73365': }
      class { '::secure_windows::stig::v73369': }
      class { '::secure_windows::stig::v73371': }
      class { '::secure_windows::stig::v73373': }
      class { '::secure_windows::stig::v73375': }
      class { '::secure_windows::stig::v73377': }
      class { '::secure_windows::stig::v73379': }
      class { '::secure_windows::stig::v73387': }
      class { '::secure_windows::stig::v73389': }
      class { '::secure_windows::stig::v73391': }
      class { '::secure_windows::stig::v73393': }
      class { '::secure_windows::stig::v73395': }
      class { '::secure_windows::stig::v73397': }
      class { '::secure_windows::stig::v73399': }
      class { '::secure_windows::stig::v73405': }
      class { '::secure_windows::stig::v73407': }
      class { '::secure_windows::stig::v73409': }
      class { '::secure_windows::stig::v73411': }
      class { '::secure_windows::stig::v73413': }
      class { '::secure_windows::stig::v73415': }
      class { '::secure_windows::stig::v73417': }
      class { '::secure_windows::stig::v73419': }
      class { '::secure_windows::stig::v73421': }
      class { '::secure_windows::stig::v73423': }
      class { '::secure_windows::stig::v73425': }
      class { '::secure_windows::stig::v73427': }
      class { '::secure_windows::stig::v73429': }
      class { '::secure_windows::stig::v73431': }
      class { '::secure_windows::stig::v73433': }
      class { '::secure_windows::stig::v73435': }
      class { '::secure_windows::stig::v73437': }
      class { '::secure_windows::stig::v73439': }
      class { '::secure_windows::stig::v73441': }
      class { '::secure_windows::stig::v73443': }
      class { '::secure_windows::stig::v73445': }
      class { '::secure_windows::stig::v73447': }
      class { '::secure_windows::stig::v73449': }
      class { '::secure_windows::stig::v73451': }
      class { '::secure_windows::stig::v73453': }
      class { '::secure_windows::stig::v73455': }
      class { '::secure_windows::stig::v73457': }
      class { '::secure_windows::stig::v73459': }
      class { '::secure_windows::stig::v73461': }
      class { '::secure_windows::stig::v73463': }
      class { '::secure_windows::stig::v73465': }
      class { '::secure_windows::stig::v73467': }
      class { '::secure_windows::stig::v73469': }
      class { '::secure_windows::stig::v73471': }
      class { '::secure_windows::stig::v73473': }
      class { '::secure_windows::stig::v73475': }
      class { '::secure_windows::stig::v73477': }
      class { '::secure_windows::stig::v73479': }
      class { '::secure_windows::stig::v73481': }
      class { '::secure_windows::stig::v73483': }
      class { '::secure_windows::stig::v73485': }
      class { '::secure_windows::stig::v73487': }
      class { '::secure_windows::stig::v73489': }
      class { '::secure_windows::stig::v73491': }
      class { '::secure_windows::stig::v73493': }
      class { '::secure_windows::stig::v73495': }
      class { '::secure_windows::stig::v73497': }
      class { '::secure_windows::stig::v73499': }
      class { '::secure_windows::stig::v73501': }
      class { '::secure_windows::stig::v73503': }
      class { '::secure_windows::stig::v73505': }
      class { '::secure_windows::stig::v73507': }
      class { '::secure_windows::stig::v73509': }
      class { '::secure_windows::stig::v73511': }
      class { '::secure_windows::stig::v73513': }
      class { '::secure_windows::stig::v73515': }
      class { '::secure_windows::stig::v73517': }
      class { '::secure_windows::stig::v73521': }
      class { '::secure_windows::stig::v73525': }
      class { '::secure_windows::stig::v73527': }
      class { '::secure_windows::stig::v73529': }
      class { '::secure_windows::stig::v73531': }
      class { '::secure_windows::stig::v73533': }
      class { '::secure_windows::stig::v73535': }
      class { '::secure_windows::stig::v73537': }
      class { '::secure_windows::stig::v73539': }
      class { '::secure_windows::stig::v73541': }
      class { '::secure_windows::stig::v73543': }
      class { '::secure_windows::stig::v73545': }
      class { '::secure_windows::stig::v73547': }
      class { '::secure_windows::stig::v73549': }
      class { '::secure_windows::stig::v73551': }
      class { '::secure_windows::stig::v73553': }
      class { '::secure_windows::stig::v73555': }
      class { '::secure_windows::stig::v73557': }
      class { '::secure_windows::stig::v73559': }
      class { '::secure_windows::stig::v73561': }
      class { '::secure_windows::stig::v73563': }
      class { '::secure_windows::stig::v73565': }
      class { '::secure_windows::stig::v73567': }
      class { '::secure_windows::stig::v73569': }
      class { '::secure_windows::stig::v73571': }
      class { '::secure_windows::stig::v73573': }
      class { '::secure_windows::stig::v73575': }
      class { '::secure_windows::stig::v73577': }
      class { '::secure_windows::stig::v73579': }
      class { '::secure_windows::stig::v73581': }
      class { '::secure_windows::stig::v73583': }
      class { '::secure_windows::stig::v73585': }
      class { '::secure_windows::stig::v73587': }
      class { '::secure_windows::stig::v73589': }
      class { '::secure_windows::stig::v73591': }
      class { '::secure_windows::stig::v73593': }
      class { '::secure_windows::stig::v73595': }
      class { '::secure_windows::stig::v73597': }
      class { '::secure_windows::stig::v73599': }
      class { '::secure_windows::stig::v73601': }
      class { '::secure_windows::stig::v73603': }
      class { '::secure_windows::stig::v73605':
        is_dod         => $is_dod,
        classification => $classification,
      }
      class { '::secure_windows::stig::v73607':
        is_dod         => $is_dod,
        classification => $classification,
      }
      class { '::secure_windows::stig::v73609':
        is_dod         => $is_dod,
        classification => $classification,
      }
      class { '::secure_windows::stig::v73611': }
      class { '::secure_windows::stig::v73621': }
      class { '::secure_windows::stig::v73623': }
      class { '::secure_windows::stig::v73625': }
      class { '::secure_windows::stig::v73627': }
      class { '::secure_windows::stig::v73629': }
      class { '::secure_windows::stig::v73631': }
      class { '::secure_windows::stig::v73633': }
      class { '::secure_windows::stig::v73635': }
      class { '::secure_windows::stig::v73637': }
      class { '::secure_windows::stig::v73639': }
      class { '::secure_windows::stig::v73641': }
      class { '::secure_windows::stig::v73643': }
      class { '::secure_windows::stig::v73645': }
      class { '::secure_windows::stig::v73647': }
      class { '::secure_windows::stig::v73649': }
      class { '::secure_windows::stig::v73651': }
      class { '::secure_windows::stig::v73653': }
      class { '::secure_windows::stig::v73655': }
      class { '::secure_windows::stig::v73657': }
      class { '::secure_windows::stig::v73659': }
      class { '::secure_windows::stig::v73661': }
      class { '::secure_windows::stig::v73663': }
      class { '::secure_windows::stig::v73665': }
      class { '::secure_windows::stig::v73667': }
      class { '::secure_windows::stig::v73669': }
      class { '::secure_windows::stig::v73671': }
      class { '::secure_windows::stig::v73673': }
      class { '::secure_windows::stig::v73675': }
      class { '::secure_windows::stig::v73677': }
      class { '::secure_windows::stig::v73679': }
      class { '::secure_windows::stig::v73681': }
      class { '::secure_windows::stig::v73683': }
      class { '::secure_windows::stig::v73685': }
      class { '::secure_windows::stig::v73687': }
      class { '::secure_windows::stig::v73689': }
      class { '::secure_windows::stig::v73691': }
      class { '::secure_windows::stig::v73693': }
      class { '::secure_windows::stig::v73695': }
      class { '::secure_windows::stig::v73697': }
      class { '::secure_windows::stig::v73699': }
      class { '::secure_windows::stig::v73701': }
      class { '::secure_windows::stig::v73703': }
      class { '::secure_windows::stig::v73705': }
      class { '::secure_windows::stig::v73707': }
      class { '::secure_windows::stig::v73709': }
      class { '::secure_windows::stig::v73711': }
      class { '::secure_windows::stig::v73713': }
      class { '::secure_windows::stig::v73715': }
      class { '::secure_windows::stig::v73717': }
      class { '::secure_windows::stig::v73719': }
      class { '::secure_windows::stig::v73721': }
      class { '::secure_windows::stig::v73723': }
      class { '::secure_windows::stig::v73725': }
      class { '::secure_windows::stig::v73727': }
      class { '::secure_windows::stig::v73729': }
      class { '::secure_windows::stig::v73731': }
      class { '::secure_windows::stig::v73733': }
      class { '::secure_windows::stig::v73735': }
      class { '::secure_windows::stig::v73737': }
      class { '::secure_windows::stig::v73739': }
      class { '::secure_windows::stig::v73741': }
      class { '::secure_windows::stig::v73743': }
      class { '::secure_windows::stig::v73745': }
      class { '::secure_windows::stig::v73747': }
      class { '::secure_windows::stig::v73749': }
      class { '::secure_windows::stig::v73751': }
      class { '::secure_windows::stig::v73753': }
      class { '::secure_windows::stig::v73755': }
      class { '::secure_windows::stig::v73757': }
      class { '::secure_windows::stig::v73759': }
      class { '::secure_windows::stig::v73761': }
      class { '::secure_windows::stig::v73763': }
      class { '::secure_windows::stig::v73765': }
      class { '::secure_windows::stig::v73767': }
      class { '::secure_windows::stig::v73769': }
      class { '::secure_windows::stig::v73771': }
      class { '::secure_windows::stig::v73773': }
      class { '::secure_windows::stig::v73775': }
      class { '::secure_windows::stig::v73777': }
      class { '::secure_windows::stig::v73779': }
      class { '::secure_windows::stig::v73781': }
      class { '::secure_windows::stig::v73783': }
      class { '::secure_windows::stig::v73785': }
      class { '::secure_windows::stig::v73787': }
      class { '::secure_windows::stig::v73789': }
      class { '::secure_windows::stig::v73791': }
      class { '::secure_windows::stig::v73793': }
      class { '::secure_windows::stig::v73795': }
      class { '::secure_windows::stig::v73797': }
      class { '::secure_windows::stig::v73799': }
      class { '::secure_windows::stig::v73801': }
      class { '::secure_windows::stig::v73803': }
      class { '::secure_windows::stig::v73807': }
      class { '::secure_windows::stig::v73809': }

    }

    default: {
      fail("Unsupported operating system (${facts['operatingsystemmajrelease']}) detected.")
    }

  }
}
